parameters:
#    service.example.class: Karis\ServiceBundle\Example

services:
#    service.example:
#        class: %service.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
